import NextAuth from "next-auth";
import createMiddleware from "next-intl/middleware";

import { routing } from "@/i18n/routing";
import { authConfig } from "./auth.config";

const { auth } = NextAuth(authConfig);

const intlMiddleware = createMiddleware(routing);

export default auth((req) => {
  //? 1. Run the internationalization middleware
  const response = intlMiddleware(req);

  //? Runs only if the cookie does not exist
  if (!req.cookies.has("sessionCartId")) {
    const sessionCartId = crypto.randomUUID();

    //? Set the cookie in the response generated by next-intl
    response.cookies.set("sessionCartId", sessionCartId);
  }

  return response;
});

/**
 * Matcher configuration typically used by Next.js Middleware to identify
 * which paths should trigger the internationalization logic.
 */
export const config = {
  matcher: ["/((?!api|_next|.*\\..*).*)"],
};
